name: instagramui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
     sdk: flutter
  flutter_svg: 2.0.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/instagramlogo.png
  - assets/Oval.png
  - assets/Facebook.png
  - assets/camera.png
  - assets/igtv.png
  - assets/send.png
  - assets/ajmal.jpg
  - assets/sanin.jpg
  - assets/badusha.jpg
  - assets/bilal.jpg
  - assets/rihan.jpg
  - assets/nubl.jpg
  - assets/naheel.jpg
  - assets/feril.jpg
  - assets/thamjid.jpg
  - assets/ashmel.jpg
  - assets/post.jpg
  - assets/comment.png
  - assets/scan.png
  - assets/bike.jpg
  - assets/car1.jpg
  - assets/car2.jpg
  - assets/car3.jpg
  - assets/car4.jpg